### ISSUE TITLE
console error in marble implementation

### ISSUE THREAD

**Issue by mutdmour** [stonega/vue2-boring-avatars#5]
Console error in marble impelmentation
```
 <path> attribute transform: Expected ')', "translate(0 0 rotate(96 40 40)…"
```

<img width="936" alt="Screen Shot 2021-09-27 at 3 03 00 PM" src="https://user-images.githubusercontent.com/4711238/134913668-2d93264e-470b-4fa5-a34e-647666fb3c5b.png">

**Comment by stonega** [comment]
Thanks for the pr, I have published a new version with this fix.
