### ISSUE TITLE
Transparent background in Marble

### ISSUE THREAD

**Issue by nicodemus-opon** [stonega/vue2-boring-avatars#9]
Hi, marble seems to have a transparent background as seen below...you can even confirm on the demo site
<img width="678" alt="Screenshot 2021-12-09 at 14 45 10" src="https://user-images.githubusercontent.com/36782985/145391984-bd102689-2525-4f5d-9f16-d18bf51b33f9.png">
however it should look like the image below
<img width="604" alt="Screenshot 2021-12-09 at 14 45 20" src="https://user-images.githubusercontent.com/36782985/145392198-f4b5c409-c0ca-486a-81d0-a34954dd6d53.png">

I have created a PR fixing the issue.

**Comment by stonega** [comment]
Cool, Thanks！ Merged and updated.

**Comment by nicodemus-opon** [comment]
could you please publish it to npm

**Comment by stonega** [comment]
> could you please publish it to npm
> 

Published already, please have a check.😄

**Comment by nicodemus-opon** [comment]
> > could you please publish it to npm
> 
> Published already, please have a check.😄

latest version on npm is 0.3.4...i think we're at 0.3.6 or does it take a while for the new version to appear on npm?

**Comment by stonega** [comment]
> > > could you please publish it to npm
> > 
> > 
> > Published already, please have a check.smile
> 
> latest version on npm is 0.3.4...i think we're at 0.3.6 or does it take a while for the new version to appear on npm?

Version 0.3.6 is alreay available on npm i think, can you confirm that?

**Comment by nicodemus-opon** [comment]
> > > > could you please publish it to npm
> > > 
> > > 
> > > Published already, please have a check.smile
> > 
> > 
> > latest version on npm is 0.3.4...i think we're at 0.3.6 or does it take a while for the new version to appear on npm?
> 
> Version 0.3.6 is alreay available on npm i think, can you confirm that?

Hi, i've tried it but i'm getting the error below
```
 ERROR  Failed to compile with 1 error                                                                  19:02:57

This dependency was not found:

* vue2-boring-avatars in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/View.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save vue2-boring-avatars
```

version 0.3.5 worsk well though

**Comment by stonega** [comment]
@nicodemus-opon  Have you solved the issue? I tested to install the package and it worked.

**Comment by nicodemus-opon** [comment]
i'm still getting the same error...let me close the issue though, might be a problem on my side
